# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: devon_mar
name: nblists
version: 0.1.0
readme: README.md
authors:
  - Devon Mar (https://github.com/devon-mar)
description: Plugins for the NetBox Lists plugin for NetBox.
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - netbox
  - netbox_lists
repository: https://github.com/devon-mar/ansible-collection-nblists
documentation: https://devon-mar.github.io/ansible-collection-nblists/
homepage: https://github.com/devon-mar/ansible-collection-nblists
issues: https://github.com/devon-mar/ansible-collection-nblists
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .github
  - docs
  - tests
  - .vscode
  - codecov.yml
  - MAINTAINERS
