---
# https://github.com/ansible-community/github-docs-build/blob/main/samples/push-with-publish-to-gh-pages.yml
name: Collection Docs
concurrency:
  group: collection-docs
  cancel-in-progress: false
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 13 * * *"

jobs:
  build-publish-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/ansible_collections/devon_mar/nblists

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install antsibull-docs
        run: pip install antsibull-docs

      - name: Build docs
        run: |
          pip install -r requirements.txt
          ./build.sh
        working-directory: ${{ github.workspace }}/ansible_collections/docs/
        env:
          ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}/ansible_collections

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: build/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
